config/routes.rb
Rails.application.routes.draw do
  resources :question do
    collection do
      get "ScoreQuestion"
      get "admin_indexquestion"
      get "user_indexquestion"
      get "add_userquestion"
    end
  end
  resources :testofuser do

  end
  resources :user
  devise_for :users
  get 'search',to: "testofuser#search"
  as :user do 
    root to: "home#show"
    get "login" => "devise/sessions#new"
    post "login" => "devise/sessions#create"
    delete "logout" => "devise/sessions#destroy"
   # get "profile" =>"devise/User"

  end

 
 
  get 'queston/ScoreQuestion'
  get 'test/ViewallTest'
  # get "question/:id/edit" => "question#edit"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
  

app/models/question.rb
class Question < ApplicationRecord
  validates :quetion  , presence: true
  has_many :answer, dependent: :destroy
  validates_length_of :answer, maximum: 8
  accepts_nested_attributes_for :answer, allow_destroy: true, reject_if: :all_blank, limit: 8
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy get_user_indexquestion add_userquestion]

  def index
    @question_admin = Question.order(:id)
    id_of_question = Array.new
    @question = Question.where(level: params[:level_Question], role: (params[:topic]), Belongto: "admin").order("RANDOM()").limit(params[:Num_Question])
    @question.each do |question|  
    id_of_question.push(question[:id].to_i)
  end
    @id_question  = id_of_question.sort
  end
  def new
    @question = Question.new
  end
  def show  

  end
  def ScoreQuestion
    listQuestion = params[:id_of_question].tr('[]', '').split(',').map(&:to_i)
    @question = Question.where('id IN (?)', listQuestion)
  end
  def admin_indexquestion
    @pagy, @question = pagy(Question.order(:id).where(Belongto: "admin"), items: 30)
  end
  def user_indexquestion
    @pagy, @question = pagy(Question.order(:id).where.not(Belongto: "admin"), items: 30)
  end
  def add_userquestion
  
  end
  def edit  
   
  end

  def create
    @question = Question.new(question_params) 
    respond_to do |format|
      if @question.save
        format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /questions/1 or /questions/1.json
  def update    
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
        puts "thanh cong"
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end 
    end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    if @question.present?
      @question.destroy
    end
    redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:quetion, :role, :level,:Belongto, answer_attributes: [:id,:moreans,:check, :_destroy])
    end
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/question/ScoreQuestion.html.erb
<header>
  <h1>Your Test</h1>
</header>
<%anser = String.new%>
<%id_of_question = params[:id_of_question]%>
<%= hidden_field_tag :remaining_time, @remaining_time %>
<%score = 0%>
<%count =0%>
<%hs = 10/(params[:num_of_question].to_f)%>           
<%@question.each do |question|%> 
 <%count = count +1%>
 <div class="quiz-container" id="quiz"> 
    <div class="quiz-header">
  <div style="font-weight: bold; font-size : 1.25em">Question Number <%=count%>:<br> </div>
  <div><%= question['quetion'] %></div>
      <ul> 
      <%anser = anser + question['id'].to_s+":"%>
      <%if params[(question[:id]).to_s].present?%>
        <%anser = anser + params[(question[:id]).to_s]+","%>
      <%else%>
        <%anser = anser + "not anser,"%>
      <%end%>
        <%if question.answer.any?%>
          <% question.answer.each do |ans| %>  
           <td>
             <%user_ans =params[(question[:id]).to_s] %>
            <%if ans.check %>
              <%color = "green"%>
              <%if ans.id.to_s.eql? user_ans%>
                <%score = score + hs%>
              <%end%>
            <%else%>
              <%if !params[(question[:id]).to_s].present? or ans.id.to_s.eql? user_ans%>
                <%color = "red"%>
              <%else%>
                <%color = "black"%>
              <%end%>
            <%end%> 
            <p style="color:<%=color%>"> <%= ans.moreans %></p> 
        </td>   
          <%end%>
      </ul>   
      <%end%>
        </div>
    </div>
  <% end %>
  <%test_of_users = Testofuser.new()%>
  <%test_of_users.idofuser = current_user.id.to_s%>
  <%test_of_users.test = anser%>
  <%test_of_users.score = score.round(2)%>
  <%test_of_users.topic = params[:topic]%>
  <%test_of_users.save%>  
  <%ExampleMailer.sample_email(current_user).deliver_now%>
<h1>your score: <%=score.round(2)%></h1>
<%= link_to 'Do it again', question_index_path(:Num_Question => params["num_of_question"]) %>
<footer>
  <p>View my project <a href="#">NguyenExam&trade;</a></p>
</footer>

app/views/question/_answer_fields.html.erb
<div class="nested-fields">
      <%= f.label :moreans , style: "display: block"%>
      <%= f.text_field :moreans %>
      <%= f.check_box :check %>
      <%= f.hidden_field :_destroy %>
    <div>
      <%= link_to "Remove", '#', class: "remove_fields" %>
    </div>
</div>

app/views/question/_form.html.erb
<%= form_with(model: @question , local: true, mothod: :GET, url: { action: "create" }) do |f| %> 
 <%if @question.errors.any?%>
    <div style="color: red">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
        <%@question.errors.each do |error|%>  
          <li><%= error.full_message %></li>
        <%end%>
      </ul>
    </div>
  <%end%>
<%count =4%>
<h2>Enter user details</h2>
   <div>
    <%= f.label :quetion, style: "display: block" %>
    <%= f.text_field :quetion %>
  </div>  
  <div class="nested-fields">
   <%= f.fields_for :answer, Answer.new do |b| %>
    <%render("answer_fields", f: b)%>
    <% end %>
</div>
  <div class="nested-fields">
   <%= f.fields_for :answer, Answer.new do |b| %>
    <%render("answer_fields", f: b)%>
    <% end %>
</div>
  <div class="nested-fields">
   <%= f.fields_for :answer, Answer.new do |b| %>
    <%render("answer_fields", f: b)%>
    <% end %>
</div>
  <div class="nested-fields">
   <%= f.fields_for :answer, Answer.new do |b| %>
    <%render("answer_fields", f: b)%>
    <% end %>
</div>  
<div>
  <%=link_to_add_fields "Add answer", f, :answer %> 
</div>
<div>   
  <div>
    <%= f.label :role, style: "display: block" %>
    <%= f.text_field :role %>
  </div>
  <div>
    <%= f.label :level, style: "display: block" %>
    <%= f.select :level, options_for_select([["ez", "ez"], ["normal", "normal"],["hard", "hard"],["very hard", "very hard"]]) %>
  </div>
  <%= f.hidden_field :Belongto , :value => current_user.username  %>
<div>
  <%= f.submit %>
</div>  
<% end %>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script type="text/javascript">
var $check_boxes = $('input[type=checkbox]');
$check_boxes.click(function() {
  $check_boxes.prop('checked', false);
  $(this).prop('checked', true);
});
</script>

app/views/question/_formtest.html.erb
<%= form_with(model: question) do |form| %>

<h2>
   <div>
    <%= form.label :quetion, style: "display: block" %>
    <%= form.text_field :quetion %>
  </div>

  <div>
    <%= form.label :a1, style: "display: block" %>
    <%= form.check_box  :a1 %>
  </div>

  <div>
    <%= form.label :a2, style: "display: block" %>
    <%= form.check_box :a2 %>
  </div>

  <div>
    <%= form.label :a3, style: "display: block" %>
    <%= form.check_box :a3 %>
  </div>

  <div>
    <%= form.label :a4, style: "display: block" %>
    <%= form.check_box :a4 %>
  </div>
</h2>
    <%= form.submit %>
  </div>
<% end %>

app/views/question/_question.erb
<%count =1%>
  <p>
    <strong>question:</strong>
    <%= @question.quetion %>
  </p>
  <%if @question.answer.any?%>  
      <% @question.answer.each do |ans| %>
        <p>
        <%color = "black"%>
        <%if ans.check ==true%> 
          <%color = "green"%>
        <%end%>
        <strong> <p style="color:<%=color%>">ans <%=count%> : <%= ans.moreans %></p></strong>
        <%count = count +1%>
        </p>   
      <%end%>
    <%end%>
  <p> 
    <strong> type:</strong>
    <%= @question.role %>
  </p>
  <p>
    <strong> level:</strong>
    <%= @question.level %>
  </p>

app/views/question/_show_list_question.html.erb
  <div class="editques-container">
<table>
  <thead>
    <tr class="editques">
      <th>ID</th>
      <th>Question</th>
      <th>Anser 1</th>
      <th>Anser 2</th>
      <th>Anser 3</th>
      <th>Anser 4</th>
      <th>Anser 5</th>
      <th>Anser 6</th>
      <th>Anser 7</th>
      <th>Anser 8</th>
      <th>topic</th>
      <th>level</th>
      <th colspan="3">action</th>
    </tr>
  </thead>
  <tbody>
    <% @question.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= question.quetion %></td>
      <div>
      <%count=0%>
       <%if question.answer.any?%>
          <% question.answer.each do |ans| %>
            <td>
              <%color = "black"%>
              <%if ans.check ==true%> 
                <%color = "green"%>
              <%end%>
              <p style="color:<%=color%>"> <%= ans.moreans %></p>
        <%count = count +1%>
        </td>   
          <%end%>
          <%while count<8%> 
               <td></td>
                    <%count = count +1%>
          <%end%>
        <%end%>
        </div>
        <td><%= question.role%></td>
        <td><%= question.level%></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'destroy', question, method: :delete, data: {confirm: 'Are you sure?'}%></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
<%== pagy_nav(@pagy) %>

app/views/question/add_userquestion.html.erb
   <header>
        <h1>Manager Question</h1>
    </header>
    <body>
      <%@question.Belongto = "admin"%>
      <%@question.save%>
      <meta http-equiv="Refresh" content="0; url='http://localhost:3000/question/user_indexquestion'" />
    </body>
<footer>
  <p>View my project <a href="#">NguyenExam&trade;</a></p>
</footer>

app/views/question/admin_indexquestion.html.erb
   <header>
        <h1>Manager Question</h1>
    </header>
<%=render "show_list_question"%>
<%= link_to 'New Question', new_question_path %>
<footer>
  <p>View my project <a href="#">NguyenExam&trade;</a></p>
</footer>

app/views/question/edit.html.erb
<header>
  <h1>Editing Question</h1>
</header>

<%= form_with model: @question ,local: true, mothod: :POST, url: { action: "update" } do |f| %> 
<div class="editquestion-contanier">
<% if @question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% @question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<h2>Enter user details</h2>
  <div>
    <%= f.label :quetion, style: "display: block" %>
    <%= f.text_field :quetion %>
  </div>
  <div>
  <div class="nested-fields">
  <%= f.fields_for :answer do |b| %>
    <%render("answer_fields", f: b)%>
  <%end%>
</div>  
  </div>
  <div>
    <%=link_to_add_fields "Add answer", f, :answer %> 
</div>
 <div>
    <%= f.label :role, style: "display: block" %>
    <%= f.text_field :role %>
  </div>
<div>
    <%= f.label :level, style: "display: block" %>
     <%= f.select :level, options_for_select([["ez", "ez"], ["normal", "normal"],["hard", "hard"]]) %>
  </div>
</div>
    <%= f.submit %>
  </div>

<% end %>


</div>
<footer>
  <p>View my project <a href="#">NguyenExam&trade;</a></p>
</footer>

app/views/question/index.html.erb
<% score = 0,count =0%>
<header>
  <h1>Question</h1>
</header>
<%if user_signed_in?%>
<form  action="/question/ScoreQuestion" method = "get" id = "question_Form">
 <input type="hidden" id="num_of_question" name="num_of_question" value = "<%=params[:Num_Question]%>" >
  <input type="hidden" id="id_of_question" name="id_of_question" value = "<%=@id_question%>" >
  <input type="hidden" id="topic" name="topic" value = "<%=params[:topic]%>" >
    
<div class="card">
<span id="countdown" style="font-weight: bold;"></span>
</div>
<div class="test-continer">
 <%@question.each do |question|%> 
 <%countans = 0%>
 <%if count < params["Num_Question"].to_i%>
 <%count = count +1%>
 <div class="quiz-container" id="quiz"> 
    <div class="quiz-header">
  <div style="font-weight: bold; font-size : 1.25em">Question Number <%=count%>:<br> </div>
  <div><%= question['quetion'] %></div>
      <ul> 
        <%if question.answer.any?%>
          <% question.answer.each do |ans| %>
          <li>
          <%countans =countans +1%>
          <input type="radio" name="<%=question['id']%>" id=<%=countans%> value= <%=ans.id%> class="answer">
          <td><%=ans.moreans%></td>
          </li>
          <%end%>
        <%end%>
      </ul>   
      <%end%>
    </div>
</div>
    <% end %>
  <button id="submit" onclick="submitForm()">Submit</button>
</form>
<script>
var timeInSecs;
var ticker;
function param(name) {
    return (location.search.split(name + '=')[1] || '').split('&')[0];
}
function submitForm(){
    const submitFormFunction = Object.getPrototypeOf(question_Form).submit;
    submitFormFunction.call(question_Form);
}
timmer = param("Num_Question");
function startTimer(secs) {
    timeInSecs = parseInt(secs);
    ticker = setInterval("tick()", 1000);
}
function submitForm(){
    const submitFormFunction = Object.getPrototypeOf(question_Form).submit;
    submitFormFunction.call(question_Form);
}
function tick() {
    var secs = timeInSecs;
    if (secs > 0) {
        timeInSecs--;
    } else {
     clearInterval(ticker);
     submitForm();
    }
    var mins = Math.floor(secs / 60);
    secs %= 60;
    var pretty = ((mins < 10) ? "0" : "") + mins + ":" + ((secs < 10) ? "0" : "") + secs;
    document.getElementById("countdown").innerHTML = pretty;
}
startTimer(60*timmer); //   4 minutes in seconds
//Credits to Gulzaib from Pakistan
</script>
<%end%>
<br>
<footer>
  <p>View my project <a href="#">NguyenExam&trade;</a></p>
</footer>

app/views/question/new.html.erb
<header>
  <h1>New Question</h1>
</header>
<div class="newques_container">
  <%= render "form" %>
  <%= link_to 'Back', question_index_path %>
</div>
<footer>
  <p>View my project <a href="#">NguyenExam&trade;</a></p>
</footer>

app/views/question/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="showquestion-container">
  <div class="showq">
    <%= render "question/question" %>
  </div >
  <%= link_to "Edit this question", edit_question_path(@question) %> 
  <%= button_to "Destroy this question", @question, method: :delete %>
</div>
<footer>
  <p>View my project <a href="#">NguyenExam&trade;</a></p>
</footer>

app/views/question/user_indexquestion.html.erb
   <header>
        <h1>Manager Question</h1>
    </header>
   <div class="editques-container">
<table>
  <thead>
    <tr class="editques">
      <th>ID</th>
      <th>Question</th>
      <th>Anser 1</th>
      <th>Anser 2</th>
      <th>Anser 3</th>
      <th>Anser 4</th>
      <th>Anser 5</th>
      <th>Anser 6</th>
      <th>Anser 7</th>
      <th>Anser 8</th>
      <th>topic</th>
      <th>level</th>  
      <th>Belong to user<th>
      <th colspan="3">action</th>
    </tr>
  </thead>
  <tbody>
    <% @question.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= question.quetion %></td>
      <div>
      <%count=0%>
       <%if question.answer.any?%>
          <% question.answer.each do |ans| %>
            <td>
              <%color = "black"%>
              <%if ans.check ==true%> 
                <%color = "green"%>
              <%end%>
              <p style="color:<%=color%>"> <%= ans.moreans %></p>
        <%count = count +1%>
        </td>   
          <%end%>
          <%while count<8%>
            <td></td>
            <%count = count +1%>
          <%end%>
        <%end%>
        </div>
        <td><%= question.role%></td>
        <td><%= question.level%></td>
        <td><%= question.Belongto %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'destroy', question, method: :delete, data: {confirm: 'Are you sure?'}%></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
<%== pagy_nav(@pagy) %>
<footer>
  <p>View my project <a href="#">NguyenExam&trade;</a></p>
</footer>

app/views/question/view_all_test.html.erb
hello