config/routes.rb
Rails.application.routes.draw do
  resources :question do
    collection do
      get "ScoreQuestion"
      get "admin_indexquestion"
      get "user_indexquestion"
      get "add_userquestion"
    end
  end
  resources :testofuser do

  end
  resources :user
  devise_for :users
  get 'search',to: "testofuser#search"
  as :user do 
    root to: "home#show"
    get "login" => "devise/sessions#new"
    post "login" => "devise/sessions#create"
    delete "logout" => "devise/sessions#destroy"
   # get "profile" =>"devise/User"

  end

 
 
  get 'queston/ScoreQuestion'
  get 'test/ViewallTest'
  # get "question/:id/edit" => "question#edit"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
  

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">NguyenExam</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to 'Sign out', destroy_user_session_path,method: :delete , class: 'nav-link'%>
          <% if current_user.role == "admin"%>
            <li class="nav-item"> 
              <%= link_to 'Manager Question',  admin_indexquestion_question_index_path, class: 'nav-link'%>
            </li>
            <li class="nav-item"> 
              <%= link_to 'Manager Account',  user_index_path, class: 'nav-link'%>
            </li>
            <li class="nav-item"> 
              <%= link_to 'View All User Test', testofuser_index_path, class: 'nav-link'%>
            </li>
            <li class="nav-item"> 
              <%= link_to 'View All Question of User', user_indexquestion_question_index_path, class: 'nav-link'%>
            </li>
          <%else%>
        </li>
          <li class="nav-item"> 
            <%= link_to 'View All my Test', testofuser_index_path, class: 'nav-link'%>
          </li>
          <li class="nav-item"> 
            <%= link_to 'edit Password', edit_user_registration_path, class: 'nav-link'%>
          </li>
          <li class="nav-item"> 
            <%= link_to 'send question to admin', new_question_path, class: 'nav-link'%>
          </li>
        <%end%>
      <% else %>
      <li class="nav-item"> 
        <%= link_to 'Sign in', new_user_session_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Register',new_user_registration_path, class: 'nav-link'%>
      </li>
    <%end%>
  </ul>
</div>
</div>
</nav>