config/routes.rb
Rails.application.routes.draw do
  resources :question do
    collection do
      get "ScoreQuestion"
      get "admin_indexquestion"
      get "user_indexquestion"
      get "add_userquestion"
    end
  end
  resources :testofuser do

  end
  resources :user
  devise_for :users
  get 'search',to: "testofuser#search"
  as :user do 
    root to: "home#show"
    get "login" => "devise/sessions#new"
    post "login" => "devise/sessions#create"
    delete "logout" => "devise/sessions#destroy"
   # get "profile" =>"devise/User"

  end

 
 
  get 'queston/ScoreQuestion'
  get 'test/ViewallTest'
  # get "question/:id/edit" => "question#edit"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
  

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :testofuser
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.id).first_or_create do |user|
    user.username = auth.info.username
    user.password = Devise.friendly_token[0,20]
    end
  end
  def self.find_for_database_authentication warden_condition

    conditions = warden_condition.dup
      if (login = conditions.delete(:login))
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy update_password ]
    def index
      if(current_user.id ==1)
        @user= User.order(:id)
        end
    end
    def new
 
    end
    def show  
      if(current_user.id ==1)
      @user= User.order(:id)
      end
    end 
   
    def edit  
    end

   
    
    # PATCH/PUT /questions/1 or /questions/1.json
    def update
      @user = User.find(params[:id])
     if @user.update(user_params)
      redirect_to root_path, notice:"password change"
     else
      render :edit
     end
    end
  
    # DELETE /questions/1 or /questions/1.json
    def destroy
      @user = User.find(params[:id])
      if @user.present?
        @user.destroy
      end
      redirect_to root_url
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])  
      end
      # Only allow a list of trusted parameters through.
      def user_params
        params.require(:user).permit( :password,  :password_confirmation)
      end
  end
  

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_form.html.erb
<header>
  <h1>Change user password</h1>
</header>
<%= form_with model: @user, url: edit_user_path, url: { action: "update" }  do |f| %> 
<%= render "devise/shared/error_messages", resource: @user %>
<div class="field">
  <%= f.label :password, "New password" %><br />
  <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em><br />
  <% end %>
  <%= f.password_field :password, autofocus: true, autocomplete: "new-password" %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirm new password" %><br />
  <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
</div>
<div class="action">
  <%= f.submit "Change User password",class: "btn btn-primary" %>
</div>
<% end %>
<footer>
  <p>View my project <a href="#">NguyenExam&trade;</a></p>
</footer>

app/views/user/edit.html.erb
<p style="color: green"><%= notice %></p>
<div>
<%if current_user.role == "admin"%>
<div classe="edituser-contanier">

<%= render 'form', user: @user  %>
  <%= link_to "Back to list", user_path%>
  <div>
</div>
<%else%>
<h1>You don't have permision</h1>
<%end%>

app/views/user/index.html.erb
  <thead>
    <tr> <th colspan="3"></th>
    <header>
        <h1>Manager Account</h1>
    </header>
    <%count =0 %>
    </tr>
  </thead>
  <tbody>
  <div class="edituser-contanier" style="padding: 2em 4em;">
  <table>

    <tr class="edituser">
   <th>username</th>
     <th>email</th>
     <th>action</th>
    </tr>
  
  <tbody>
     <%if current_user.role== "admin" %>
       <% @user.each do |useradmin| %>
       <%if (count !=0)%>
     
    <tr class="edituser">
       <td><%=useradmin.username%> </td>
         <td><%=useradmin.email%> </td>
         <td><%= link_to 'Edit', edit_user_path(useradmin) %></td>
     </tr>
      <%end%>
      <%count = count +1%>
    <% end %>
      </tr>
    <% end %>
  </tbody>

</table>
 
</div>    
<footer>
        <p>View my project <a href="#">NguyenExam&trade;</a></p>
    </footer>

app/views/user/show.html.erb
<p style="color: green"><%= notice %></p>
<div>
<%if current_user.role == "admin"%>
<%= render "user/user" %>
  <%= link_to "Back to list", testofuser_path%>
<%else%>
<h1>You don't have permision</h1>
<%end%>
</div>